### ISSUE TITLE
Feature request - `curry` utility

### ISSUE THREAD

**Issue by inhibitor1217** [marpple/FxTS#12]
# Suggestion

## ⭐ Suggestion

`curry` is an essential utility for FP, yet most libraries (especially `lodash`) fail to provide correct type definition.
Are there any plans for exporting `curry`? (since other utilities from `fxts` support currying, as I noticed)

## 💻 Use Cases

```typescript
const strictEq = curry(<T>(left: T, right: T) => left === right)

const twos = pipe([1, 1, 1, 2, 2, 2], filter(strictEq(2))) // [2, 2, 2]
```

**Comment by ppeeou** [comment]
Thank you for your interest.

We would consider supporting `curry`

**Comment by hg-pyun** [comment]
Will a new `curryN` function also be added?
https://github.com/marpple/FxJS/blob/2bbcebc2cdcb86d542811c45629b9f467fd49420/Strict/curryN.js

**Comment by ppeeou** [comment]
@hg-pyun  In fxts using typescript, it seems better to use `curry` like `curryN`. What do you think?

```ts
const add = (a:number, b:number, c:number) => a + b + c;
const curriedAdd = curry(add);
curriedAdd(1)(2)(3);
```
