### ISSUE TITLE
Suggest squash merge when merged main branch

### ISSUE THREAD

**Issue by hg-pyun** [marpple/FxTS#121]
## Suggestion
Hello. If you open the main branch's command log now, you can see unnecessary merge commits mixed in. 

These noise commits do not help make pretty commitments. 

Why don't we force a square merge when we merge the main branch?

## Image
![image](https://user-images.githubusercontent.com/10627668/147483852-3dea0ed7-3e40-438a-9748-af780948c013.png)

**Comment by ppeeou** [comment]
I hadn't thought deeply about this issue. I think it would be good to proceed in the way you suggested
How about @shine1594 ?

**Comment by ppeeou** [comment]
@hg-pyun 

Let's use square merge as the default
