### ISSUE TITLE
feature `dropRight`

### ISSUE THREAD

**Issue by Einere** [marpple/FxTS#134]
# Suggestion

Hello! I have used `fxjs` in my project.
And after apply typescript, i want to migrate from `fxjs` to `fxts`.
So, `fxts` API is not provide `dropRight` function yet.

## ⭐ Suggestion

please add `dropRight` function.

## 💻 Use Cases

```ts
pipe(
  [1, 2, 3, 4, 5],
  dropRight(1),
);
// [1, 2, 3, 4]
```

**Comment by ppeeou** [comment]
Thanks for your interest in fxts

In the case of `dropRight`, when it is an array, there is an advantage in lazy evaluation.
The way to use it seems to be as follows. It would be nice if you could see the test case in PR :)
https://github.com/marpple/FxTS/pull/135

```
pipe(
   [1 2 3 4 5],
   dropRight(1),
   toArray
);
```
