### ISSUE TITLE
lt, lte, gt, gte function

### ISSUE THREAD

**Issue by ppeeou** [marpple/FxTS#151]
# Suggestion

## ⭐ Suggestion

Provides a size comparison function.

It does not provide a generic type, so we are going to provide curry by default.

## 💻 Use Cases

```ts
function lte(a:number, b:number) {
  return a <= b
}

function lt(a:number, b:number) {
  return a < b
}

function gte(a:number, b:number) {
  return a >= b
}

function gt(a:number, b:number) {
  return a > b
}
```

**Comment by sunrabbit123** [comment]
Your suggestion is that
What is the difference between 'filter'?

**Comment by ppeeou** [comment]
These functions serve as auxiliary functions.
`filter` is a higher-order function that handles iterable 

If you look at how to use it, it is used as follows.
`filter(lte(5), [1,2,5,8]); // Iterable<[1,2]>`
