### ISSUE TITLE
The empty array result of the `sum` function is '0'

### ISSUE THREAD

**Issue by ppeeou** [marpple/FxTS#156]
# Suggestion

## ⭐ Suggestion

If an empty array is entered as the argument value of the [sum function](https://fxts.dev/docs/sum), undefined is output.
Returning 0 seems more natural.

as-is
```ts
const result = pipe(
 [], 
 sum
);

// result undefined
```

to-be
```ts
const result = pipe(
 [], 
 sum
);

// result 0
```

**Comment by hg-pyun** [comment]
I'll take it!

**Comment by flex-haegul** [comment]
I'm really doing it this week.

**Comment by hg-pyun** [comment]
I'm really doing it this week.

**Comment by hg-pyun** [comment]
["a", "b", "c"] that the string comes in, I don't think it's awkward to return undefined. 🤔

**Comment by ppeeou** [comment]
> @ppeeou ["a", "b", "c"] that the string comes in, I don't think it's awkward to return undefined. 🤔

@hg-pyun 
thank you for your suggestion,

I think If the `sum` function accepts only numbers, it would be better to raise a TypeError when a string(non-numeric value) is entered.
how about you??

For string connections, it would be better to use join . https://fxts.dev/docs/join
