### ISSUE TITLE
parse source map warnings when running react app

### ISSUE THREAD

**Issue by Einere** [marpple/FxTS#158]
# Bug Report

when running TS react app created by [create-react-app](https://create-react-app.dev/), webpack logs so many warnings like below. (see **Actual behavior** section)
but it does not affect for running app. just warnings.

### 💻 Code

```ts
import {filter, map, pipe, range, reduce, take } from '@fxts/core';

function App() {
  const sum = pipe(
      range(Infinity),
      filter((a) => a % 5 === 0),
      map((a) => a * 10),
      take(10),
      reduce((a, b) => a + b),
  ); // typeof 'sum' inferred as the number

  return (
    <div className="App">
    ...
    </div>
  );
}

export default App;

```

### 🙁 Actual behavior

```bash
...

WARNING in ./node_modules/@fxts/core/dist/esm/toArray.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'PROJECT_PATH/node_modules/@fxts/core/src/toArray.ts' file: Error: ENOENT: no such file or directory, open 'PROJECT_PATH/node_modules/@fxts/core/src/toArray.ts'

WARNING in ./node_modules/@fxts/core/dist/esm/unicodeToArray.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'PROJECT_PATH/node_modules/@fxts/core/src/unicodeToArray.ts' file: Error: ENOENT: no such file or directory, open 'PROJECT_PATH/node_modules/@fxts/core/src/unicodeToArray.ts'

webpack compiled with 99 warnings
No issues found.
```

### 🙂 Expected behavior

webpack logs no warning.

---

### Version Information

- Operating system: MacOS Big Sur 11.5.2
- Typescript: ^4.6.4
- Nodejs: v14.19.1

### How to reproduce

1. make react project by creat-react-app `npx create-react-app@latest ts-test --template typescript`
2. install `@fxts/core`
3. in project, use `@fxts/core` functions.
4. run react app `npm run start`

**Comment by shine1594** [comment]
Fixed in v0.6.2. Thanks for reporting the issue.
