### ISSUE TITLE
FxTS v0.3 plan

### ISSUE THREAD

**Issue by shine1594** [marpple/FxTS#20]
### Lazy
- [x] [pick & omit](https://github.com/marpple/fxts/issues/21)
- [x] [pickBy & omitBy](https://github.com/marpple/fxts/issues/45)
- [x] [pluck](https://github.com/marpple/FxTS/issues/28)
- [x] [dropWhile & dropUntil](https://github.com/marpple/FxTS/issues/22)
- [x] [zipWith](https://github.com/marpple/FxTS/issues/31)
- [x] [split](https://github.com/marpple/FxTS/issues/26)

### Strict
- [x] [join](https://github.com/marpple/fxts/issues/8)
- [x] [includes (alias as `contains`)](https://github.com/marpple/FxTS/issues/46)
- [x] [findIndex](https://github.com/marpple/fxts/issues/41)
- [x] [nth](https://github.com/marpple/FxTS/issues/47)
- [x] [sort](https://github.com/marpple/FxTS/issues/52)
- [x] [isObject](https://github.com/marpple/FxTS/issues/51)
- [x] [isNil](https://github.com/marpple/FxTS/issues/43)

### Function Composition
- [x] [curry](https://github.com/marpple/FxTS/issues/12)

**Comment by hg-pyun** [comment]
I wish I could contribute by allocating the functions scheduled here.

**Comment by ppeeou** [comment]
> I wish I could contribute by allocating the functions scheduled here.

@hg-pyun 
Of course thanks 😀

We create an issue before the start of work
the issue that has not been created is not yet worked

If there is a function you want to create, you can create an issue :)

**Comment by inflab-int** [comment]
Is there anybody who working on `curry` ? If not I want to working on.

**Comment by ppeeou** [comment]
> Is there anybody who working on `curry` ? If not I want to working on.

@inflab-int  sure 🤩

**Comment by ppeeou** [comment]
release it🎉
