### ISSUE TITLE
How about converting Typeguard function parameter type into generic type.

### ISSUE THREAD

**Issue by industriously** [marpple/FxTS#206]
# Suggestion

## ⭐ Suggestion

How about converting `Typeguard function`(is~ functions like isUndefined, isArray) into generic functions?

example

```typescript
/**
 * Returns true if `a` is a undefined.
 *
 * @example
 * ```ts
 * isUndefined(undefined); // true
 * isUndefined(2); // false
 * ```
 */
declare function isUndefined<T>(a: T): a is undefined;
export default isUndefined;
```

## 💻 Use Cases

There is an issue with using the isUndefined function and a custom generic function together, which results in the return type being `any`.

but if every is~~ function will converted into generic function, ts can type-check more properly.

example
// now @fxts/core `isUndefined` function type
<img width="348" alt="스크린샷 2023-05-24 오후 11 55 51" src="https://github.com/marpple/FxTS/assets/116284195/a133cefa-e102-4ae7-956f-46d7f061665a">

// if I convert `isUndefined` signature into generic function.
<img width="329" alt="스크린샷 2023-05-24 오후 11 54 52" src="https://github.com/marpple/FxTS/assets/116284195/df78ba2c-26ee-4c85-82b9-48e1c30089a4">

**Comment by shine1594** [comment]
I appreciate your suggestion. I will consider converting the custom-guard functions into generic functions as you proposed. However, it seems that writing it as follows may achieve the desired result:

```ts
function throwIf<T extends (...param: any) => any>(predicate: T) {
  return function <U extends Parameters<T>[0]>(input: U): U {
    if (predicate(input)) {
      throw new Error();
    } else {
      return input;
    }
  };
}
```

**Comment by industriously** [comment]
Thank you for the positive feedback. Adding to my previous response, for the isUndefined function, the following function signature would be appropriate

```typescript
declare function isUndefined<T>(input:T|undefined): input is undefined;
```

**Comment by ppeeou** [comment]
@industriously  I think it would be ok to provide a signature as you wrote
Could you please create a PR??

**Comment by industriously** [comment]
> @industriously  I think it would be ok to provide a signature as you wrote
> 
> Could you please create a PR??

sure!

**Comment by industriously** [comment]
> @industriously I think it would be ok to provide a signature as you wrote Could you please create a PR??

Can I add more function in PR??
- isDefined
- throwIf
