### ISSUE TITLE
suggest new util function `skip` and `throwError`

### ISSUE THREAD

**Issue by industriously** [marpple/FxTS#215]
# Suggestion

## ⭐ Suggestion

`skip` is a function that executes or skips certain functions in the main stream of a pipe based on conditions.

You can use the skip function in the following cases:

When you want to interrupt the main stream for certain cases.
When you want to transform data for certain cases.
When you want to perform stable type conversions for certain cases.

```ts
function skip<T, N extends T, U>(
  predicate: (input: T) => input is N,
  process: (input: Exclude<T, N>) => U,
): (input: T) => N | (U extends void ? undefined : U);

function skip<T, U>(
  predicate: (input: T) => boolean,
  process: (input: T) => U,
): (input: T) => T | (U extends void ? undefined : U);
```

`throwError` is a function like [rxjs throwError](https://rxjs.dev/api/index/function/throwError) function. just throw Error Synchronously.
I believe that using this function improves code readability.

```ts
const throwError =
  <T, E extends Error>(toError: (input: T) => E) =>
  (input: T) => {
    throw toError(input);
  };
```

## 💻 Use Cases

```ts

interface IUser {
  name: string;
  email: string;
}

interface ICreateUser {
  name?: string;
  email: string;
}

interface ICreateUserInput {
  name?: string;
  email?: string;
}

declare const isCreateUser: (input: ICreateUserInput) => input is ICreateUser;
declare const isUser: (input: ICreateUser) => input is IUser;

pipe(
  {} as ICreateUserInput,

  skip(
    isCreateUser,
    throwError(() => Error("email is required.")),
  ),

  (input: ICreateUser) => input,

  skip(
    isUser,
    ({ name, email }): IUser => ({
      name: name ?? "default name",
      email,
    }),
  ),

  (user: IUser) => {
    // save User data
  },
);

```

**Comment by industriously** [comment]
혹시 제 아이디어가 괜찮다면 pr을 남겨도 될까요? 혹은 추가로 고려하거나 개선해야될 요소가 있나요?

**Comment by ppeeou** [comment]
Thanks for your interest :) 

I think fxts is similar to libraries like ramda, lodash.

In rxjs, there are parts that [subscribe](https://rxjs.dev/api/index/function/throwError#example) to error propagation, so I think you may need a function like throw. However, it doesn't seem to be useful in fxts.

**Comment by industriously** [comment]
> Thanks for your interest :)
> 
> I think fxts is similar to libraries like ramda, lodash.
> 
> In rxjs, there are parts that [subscribe](https://rxjs.dev/api/index/function/throwError#example) to error propagation, so I think you may need a function like throw. However, it doesn't seem to be useful in fxts.

1. skip함수는 괜찮아 보이나요?
2. throwError가 rxjs의 것과 기능적으로 같다는 의미가 아니라 사용되는 형태가 유사하다는 의미였습니다. 의도적으로 에러를 throw하는 코드는 가독성이 좋지 않다고 생각합니다. throw 키워드는 삼항 연산자나 약식 arrow 함수에서 사용할 수 없습니다. 따라서 throw키워드를 사용하지 않고 원하는 에러 객체를 리턴하는 함수를 작성하기 위해 throwError 함수를 만들었습니다. 즉, throwError는 throw 키워드를 사용을 피해서 코드 가독성을 높이기 위한 용도입니다. 기존의 fxts 함수를 활용한 코드에서 혹여 (함수형 프로그래밍은 기본적으로 에러 발생코드를 지양하지만) 에러를 발생시키는 코드를 포함한다면, throwError를 사용하는 것이 꽤 좋을 것 같습니다.
혹시 그럼에도 fxts와 잘 안맞는 것 같나요?
```ts
// 기존
(num:number) => pipe(
  num,

// as-is
  (input) => { if (input < 0) throw Error(""); return input; };
// to-be
  skip((input) => input < 0, () => Error("")),

// as-is
  (input) => {
     throw Error("");
  },
// to-be
  throwError(() => Error(""))
);
```

**Comment by ppeeou** [comment]
I agree with you about improving readability.

The type is broken in the PR you uploaded. Can you fix it? https://github.com/marpple/FxTS/pull/219

**Comment by ppeeou** [comment]
it related this [pr](https://github.com/marpple/FxTS/issues/215)
