### ISSUE TITLE
Pipe require "strictNullChecks" for correct type inference

### ISSUE THREAD

**Issue by barvirm** [marpple/FxTS#224]
# Bug Report

From version 0.18 "strictNullChecks" is needed for correct type inference.

### 💻 Code
```ts
import { map, pipe } from "@fxts/core";
const sum = pipe(
    [0,1],
    map((i) => i)
)

// sum type without strictNullChecks: Promise<IterableIterator<number>>
// sum type with strictNullChecks: IterableIterator<number>
```

**Comment by ppeeou** [comment]
Thank you for creating an issue :) 
I added it to the document!

fxts recommends the tsconfig `strict:true` option.
