### ISSUE TITLE
Test of `flat.spec.ts` is broken in `main` branch

### ISSUE THREAD

**Issue by Phryxia** [marpple/FxTS#242]
# Bug Report

### 💻 Code

```
// clone FxTS to somewhere
npm install
npm test
```

### 🙁 Actual behavior

![image](https://github.com/marpple/FxTS/assets/7694910/ba52605f-669d-48bc-8d7b-0f2c8b9b8c8f)

### 🙂 Expected behavior

Test should not fail

---

### Version Information

- Operating system: Window10 WSL Ubuntu
- Typescript: Not related
- Nodejs: v16.16.0

**Comment by Phryxia** [comment]
Currently I haven't used `flat` feature so I don't know what happens. I just find this while try to fix #240.

**Comment by ppeeou** [comment]
The issue is related to the following and has not yet been resolved.

https://github.com/marpple/FxTS/issues/93
