### ISSUE TITLE
How to get string type on pipe?

### ISSUE THREAD

**Issue by freevuehub** [marpple/FxTS#264]
# Bug Report

### 💻 Code

```ts
const text = pipe(
    ['Hello', 'World'],
    toArray, // I added the code just in case...
    join(' ')
) // Promise<string>

const text = pipe<string[], string>(
    ['Hello', 'World'],
    join(' ')
) // Promise<string>

const text = join(' ', ['Hello', 'World']) // string
```

### 🙁 Actual behavior

I tried to run a pipe and get a `string` type.
However, I encountered an error saying that the type should be specified as `Promise<string>`.
Although it actually runs as a `string` without any problem, there's an error in the code.

`number` type is same..
```ts
const number = pipe(
    [1, 2, 3],
    sum
) // Promise<number>

const number = sum([1, 2, 3]) // number
```

### 🙂 Expected behavior

I want the result of the last function executed in the pipe to be specified as the final type.

like this...
```ts
const text = pipe(
    ['Hello', 'World'],
    toArray,
    join(' ')
) // string

const text = pipe<string[], string>(
    ['Hello', 'World'],
    join(' ')
) // string

const text = join(' ', ['Hello', 'World']) // string
```

---

### Version Information

- fxts/core: `0.28.0`
- Operating system: `MacOS`
- Typescript: `4.6.4`
- Nodejs: `20.7.0`

**Comment by ppeeou** [comment]
@freevuehub 
could you let me know `tsconfig`?

To get the correct inferred type from fxts, you need to use the two settings below.
`strictFunctionTypes`, `strictNullChecks`

https://fxts.dev/docs/getting-started#typescript

We recommend [strict](https://www.typescriptlang.org/tsconfig#strict) `true` to ensure correct inference.

**Comment by freevuehub** [comment]
> @freevuehub could you let me know `tsconfig`?
> 
> To get the correct inferred type from fxts, you need to use the two settings below. `strictFunctionTypes`, `strictNullChecks`
> 
> https://fxts.dev/docs/getting-started#typescript
> 
> We recommend [strict](https://www.typescriptlang.org/tsconfig#strict) `true` to ensure correct inference.


Oh... I just checked again, and it turns out I was configuring that part in a different repo.
After resetting and running it, it works well!

I will close this issue :)
