### ISSUE TITLE
sort example not working

### ISSUE THREAD

**Issue by flex-hyuntae** [marpple/FxTS#281]
# Bug Report

- Sort example is not working
- https://fxts.dev/docs/sort
 
```
sort((a, b) => a > b, [3, 4, 1, 2, 5, 2]); // [1, 2, 2, 3, 4, 5]
sort((a, b) => a > b, 'bcdaef); // ["a", "b", "c", "d", "e", "f"]
```

- but when i changed sort function like this work well
```
sort((a, b) => a - b, [3, 4, 1, 2, 5, 2]); // [1, 2, 2, 3, 4, 5]
```

### 💻 Code

- sort use Javscript Array sort method
https://github.com/marpple/FxTS/blob/main/src/sort.ts#L57C11-L57C15 
- Javascript Array sort method does not work like the docs example
<img width="360" alt="스크린샷 2024-09-10 오후 6 57 04" src="https://github.com/user-attachments/assets/756269e8-7ffc-45f8-af15-605fa646320e">

```ts

```

### 🙁 Actual behavior

```
sort((a, b) => a > b, [3, 4, 1, 2, 5, 2]); // [3, 4, 1, 2, 5, 2]
sort((a, b) => a > b, 'bcdaef); // ['b', 'c', 'd', 'a', 'e', 'f']
```

### 🙂 Expected behavior

```
sort((a, b) => a > b, [3, 4, 1, 2, 5, 2]); // [1, 2, 2, 3, 4, 5]
sort((a, b) => a > b, 'bcdaef); // ["a", "b", "c", "d", "e", "f"]
```

I don't know what the intent is

If it is intended to use '>' inside the Sort function, then the function should be fixed.
If not, I think you need to fix the example

---

### Version Information

- Operating system:
- Typescript:
- Nodejs:

**Comment by ppeeou** [comment]
@flex-hyuntae thank you for your report👍 I will fix it :)

**Comment by flex-hyuntae** [comment]
@ppeeou Hello, I mean first example also not working
