### ISSUE TITLE
bug: Error on next dev --turbo

### ISSUE THREAD

**Issue by ysm-dev** [marpple/FxTS#294]
# Bug Report

Got this error when `next dev --turbo` (tested on Next.js 15)

<img width="713" alt="image" src="https://github.com/user-attachments/assets/b29ebd4a-0271-4964-9b38-a2d50b1be33b">

### 💻 Code

```ts

```

### 🙂 Expected behavior

---

### Version Information

- Operating system: MacOS Sequoia 15.1
- Typescript: 5.6.3
- Nodejs: 22+

**Comment by ppeeou** [comment]
release 1.3.0 🎉
