### ISSUE TITLE
Return type of pipe using each isn't inferred correctly

### ISSUE THREAD

**Issue by bigsaigon333** [marpple/FxTS#36]
# Bug Report

### 💻 Code

```ts
const ex1 = pipe([1, 2, 3], each(console.log)); // const ex1: void      inferred correctly  

const ex2 = pipe([1, 2, 3], take(1), each(console.log)); //   const ex2: IterableIterator<number>     inferred incorrectly 
```

### 🙁 Actual behavior

Type of ex2 is inferred `IterableIterator<number>`

### 🙂 Expected behavior

Type of ex2 is expected to be `void`.

---

### Version Infomation

- Operating system: Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Typescript: Version 4.5.2
- Nodejs: v14.17.4
- FxTS: v.0.2.2

**Comment by ppeeou** [comment]
@bigsaigon333 
void in the return value of `each` is the intended behavior
`each` is used as a function to have an effect on the final result

If you want to return the same return value with side effects in the middle, 
check out [peek](https://fxts.dev/docs/peek). (For reference, peek is handled lazy)

**Comment by bigsaigon333** [comment]
Thanks for your kind explanation!

I understand what `each` means for :smile: 

The point is that when you use `pipe` with 3 arguments or more and the last one is `each`, 
the type of return value is not inferred as `void`. 

In below example, the type of `ex` should be void, but it is currently inferred as `IterableIterator<number>` .
```ts
const ex = pipe([1, 2, 3], take(1), each(console.log)); 
//  [expected] const ex2: void
//  [actual] const ex2: IterableIterator<number>     
```

Please kindly check the below.
<https://codesandbox.io/s/fxts-pipe-each-retury-type-2yhlt?file=/src/index.ts>

**Comment by ppeeou** [comment]
you can test v0.2.3 :)

thank you for report !

**Comment by ppeeou** [comment]
@jbl428 contribute it ! :+1:
https://github.com/marpple/FxTS/compare/v0.2.2...v0.2.3


you can test v0.2.3 :)
thank you for report !

**Comment by ppeeou** [comment]
This issue was resolved
