### ISSUE TITLE
Add search function on website

### ISSUE THREAD

**Issue by ppeeou** [marpple/FxTS#62]
# Suggestion

## ⭐ Suggestion

With more functions, the page needs a search function.

## 💻 Use Cases

![image](https://user-images.githubusercontent.com/10924072/145926377-3b28c19f-e602-4472-b099-67e4788509c3.png)

**Comment by silasabbott** [comment]
Love this—I think being able to somehow see or filter which functions take Objects and which functions take Arrays would be nice too

**Comment by ppeeou** [comment]
Thank you for your interest. As the number of functions increases, we think we need  this function as well

**Comment by ppeeou** [comment]
@silasabbott Requested crawling at https://docsearch.algolia.com/apply/
I would proceed with the issue as soon as receive the email :)

**Comment by hg-pyun** [comment]
Fantastic!
