### ISSUE TITLE
Need `join` function

### ISSUE THREAD

**Issue by 6h15m** [marpple/FxTS#8]
# Suggestion

## ⭐ Suggestion

I would like to use `join` function like other library [lodash#join](https://lodash.com/docs/4.17.15#join)

## 💻 Use Cases

```
_.join(['a', 'b', 'c'], '~');
// => 'a~b~c'
```

**Comment by iamchiwon** [comment]
simply use `join` after `toArray`
```ts
toArray(range(5)).join('-')
// 0-1-2-3-4
```

**Comment by ppeeou** [comment]
In this case, you can create `join` in one traversal
```ts
const join = (iter,sep =',') => _.reduce((acc, str)=> `${acc}${sep}${str}`, iter)])
```

**Comment by ppeeou** [comment]
it is merged ref https://github.com/marpple/FxTS/pull/15
