### ISSUE TITLE
`npm run test` failed intermittently due to timeout

### ISSUE THREAD

**Issue by ppeeou** [marpple/FxTS#93]
# Bug Report

### 💻 Code

`npm run test` failed intermittently due to timeout.

![image](https://user-images.githubusercontent.com/25566139/146245134-29e0c889-9b97-41fa-8004-45ec9ecc83fe.png)

### 🙁 Actual behavior

The `setTimeout` set in test does not match intermittently.

### 🙂 Expected behavior

The test action should always succeed.

---

### Version Infomation

- Operating system:
- Typescript:
- Nodejs: 16.3.0

**Comment by ppeeou** [comment]
We do a lot of testing asynchronous operations, and we want them to work as we intended by the correct time.

We can fail if we run jest in parallel.
execution environment
- branch: feature/jest-dockerenv
```
docker run --cpus 2 --rm -v `PWD`:/app --name fxts -it fxts:0.1 bash
npm test
```

No failure with jest maxWorkers set to 1
https://jestjs.io/docs/cli#--maxworkersnumstring

**Comment by ppeeou** [comment]
In the past, the case of failure because it took a long time does not occur, but other cases are occurring
![image](https://user-images.githubusercontent.com/10924072/147042160-fafb36fc-3713-4dc7-b78d-d1c72d7c671f.png)

**Comment by ppeeou** [comment]
https://jestjs.io/docs/timer-mocks

> Timer Mocks
The native timer functions (i.e., setTimeout, setInterval, clearTimeout, clearInterval) are less than ideal for a testing environment since they depend on real time to elapse. Jest can swap out timers with functions that allow you to control the passage of time. Great Scott!


We measure maximum and minimum times to measure time.

However, we are using `setTimeout` for the minimum time, but `setTimeout` does not seem to be suitable as a test.

https://github.com/marpple/FxTS/blob/main/test/utils.ts#L3-L5
```ts
export const callFuncAfterTime = (callback: Arrow, time = 1000) => {
  setTimeout(callback, time);
};
```

**Comment by sunrabbit123** [comment]
All tests must be passed, but some tests fail depending on the environment.
Of course, maxWorkers is 1.

![image](https://user-images.githubusercontent.com/64676070/159845384-35a096a6-73cc-4a41-b8ae-95120e32f041.png)

```
      × should be chunked after concurrent (655 ms) // around 650ms                                                                                                                                                          
      × should be chunked after concurrent with filter (1055 ms)  // around 1050ms                                                                                                                                
      × should be chunked before concurrent (1058 ms)  // around 1050ms
```
Shouldn't we lower the hurdles?


## Version Infomation
Operating system: windows11
Typescript: 
Nodejs: 16.13.2
